const { exec } = require('child_process');
const util = require('util');
const fs = require('fs');
const path = require('path');
const axios = require('axios');

const execAsync = util.promisify(exec);

const PROJECTS_DIR = process.env.PROJECTS_DIR || '/root/projects';

// ── Shell ─────────────────────────────────────────────────────
async function runCommand(cmd, cwd = '/root', timeoutMs = 20000) {
  try {
    const { stdout, stderr } = await execAsync(cmd, { cwd, timeout: timeoutMs });
    const out = (stdout + (stderr ? '\n' + stderr : '')).trim();
    return { success: true, output: out.slice(0, 2000) || '(kein Output)' };
  } catch (err) {
    return { success: false, output: (err.stderr || err.message || 'Fehler').slice(0, 2000) };
  }
}

// ── Dateisystem ───────────────────────────────────────────────
function createDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
  return dirPath;
}

function writeFile(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
}

function readFile(filePath) {
  if (!fs.existsSync(filePath)) return null;
  try { return fs.readFileSync(filePath, 'utf8'); } catch { return null; }
}

// ── GitHub API ────────────────────────────────────────────────
async function createGithubRepo(repoName, token, user) {
  try {
    const { data } = await axios.post('https://api.github.com/user/repos', {
      name: repoName,
      private: false,
      auto_init: false,
      description: 'Generated by Alex Agent',
    }, {
      headers: { Authorization: `token ${token}`, Accept: 'application/vnd.github.v3+json' },
      timeout: 10000,
    });
    // Kurz warten bis GitHub das Repo vollständig initialisiert hat
    await new Promise(r => setTimeout(r, 3000));
    return { success: true, url: data.html_url, cloneUrl: data.clone_url };
  } catch (err) {
    // Repo existiert bereits → trotzdem weitermachen
    if (err.response?.data?.message === 'Repository creation failed.') {
      await new Promise(r => setTimeout(r, 2000));
      return { success: true, url: `https://github.com/${user}/${repoName}`, cloneUrl: `https://github.com/${user}/${repoName}.git` };
    }
    return { success: false, error: err.response?.data?.message || err.message };
  }
}

async function pushToGithub(projectDir, repoName, token, user) {
  const remote = `https://${token}@github.com/${user}/${repoName}.git`;

  await runCommand('git config --global user.email "alex@agent.local"');
  await runCommand('git config --global user.name "Alex Agent"');
  await runCommand('git config --global init.defaultBranch main');

  const steps = [
    { cmd: 'git init -b main', required: true },
    { cmd: 'git add -A', required: true },
    { cmd: 'git commit -m "Initial commit by Alex Agent"', required: true },
    // Remote setzen: add oder update falls schon vorhanden
    { cmd: `git remote add origin ${remote} || git remote set-url origin ${remote}`, required: true },
    { cmd: 'git push -u origin main --force', required: true },
  ];

  for (const step of steps) {
    const result = await runCommand(step.cmd, projectDir);
    if (!result.success && step.required) {
      return { success: false, error: result.output };
    }
  }
  return { success: true };
}

async function enableGithubPages(repoName, token, user) {
  try {
    await axios.post(`https://api.github.com/repos/${user}/${repoName}/pages`, {
      source: { branch: 'main', path: '/' },
    }, {
      headers: { Authorization: `token ${token}`, Accept: 'application/vnd.github.v3+json' },
      timeout: 10000,
    });
    return `https://${user}.github.io/${repoName}`;
  } catch {
    return null;
  }
}

// ── Projekt-Dateien aus Claude-Output parsen ──────────────────
function parseProjectFiles(claudeOutput) {
  const files = [];
  // Alle ===FILE: Marker finden
  const markers = [...claudeOutput.matchAll(/===FILE:\s*(.+?)===\n/g)];
  if (markers.length === 0) return files;

  for (let i = 0; i < markers.length; i++) {
    const filename = markers[i][1].trim();
    const contentStart = markers[i].index + markers[i][0].length;

    let contentEnd;
    if (i + 1 < markers.length) {
      // Bis zum ===END=== vor dem nächsten ===FILE===
      const endPos = claudeOutput.lastIndexOf('===END===', markers[i + 1].index);
      contentEnd = endPos > contentStart ? endPos : markers[i + 1].index;
    } else {
      // Letzter Block: bis ===END=== oder EOF
      const endPos = claudeOutput.indexOf('===END===', contentStart);
      contentEnd = endPos !== -1 ? endPos : claudeOutput.length;
    }

    const content = claudeOutput.slice(contentStart, contentEnd).trim();
    if (content) files.push({ path: filename, content });
  }
  return files;
}

module.exports = {
  runCommand, createDir, writeFile, readFile,
  createGithubRepo, pushToGithub, enableGithubPages,
  parseProjectFiles, PROJECTS_DIR,
};
